"""update vector dimensions to 768

Revision ID: d9970789b992
Revises: 18f4dc2b1571
Create Date: 2026-09-14 03:50:57.655363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9970789b992'
down_revision: Union[str, Sequence[str], None] = '18f4dc2b1571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_embedding_hnsw'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_document_chunks_metadata_json_gin'), table_name='document_chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_document_chunks_search_vector_gin'), table_name='document_chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_source_documents_metadata_json_gin'), table_name='source_documents', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_source_documents_metadata_json_gin'), 'source_documents', ['metadata_json'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_chunks_search_vector_gin'), 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_chunks_metadata_json_gin'), 'document_chunks', ['metadata_json'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_chunks_embedding_hnsw'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
